"""add category to property

Revision ID: 726abff79164
Revises: 425bb14b94a1
Create Date: 2023-07-01 18:38:39.230633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726abff79164'
down_revision = '425bb14b94a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('category_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'category_title')
    # ### end Alembic commands ###
